# Generated by Django 5.2.1 on 2025-05-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatlog',
            old_name='type',
            new_name='sender',
        ),
    ]
