# Generated by Django 5.2.1 on 2025-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_rename_type_chatlog_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
